
line_length:
  warning: 150
  error: 2000
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

cyclomatic_complexity:
  warning: 15

file_length:
  warning: 600
  error: 1000

included:
- AircallMe
- Modules

trailing_whitespace:
  ignores_empty_lines: true

disabled_rules:
- identifier_name